version: '3'
services:
  dapp:
    image: bus-ticket
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    command: yarn start
